name: miv_buttons
description: Elegant pseudo 3D buttons. You can use them instead of or in addition to the standard buttons.
version: 1.0.1
homepage: https://github.com/mivoligo/miv_buttons
topics:
  - button
  - ui
  - widget
  - design
  - flutter

environment:
  sdk: ^3.5.1
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
